### ISSUE TITLE
TASK: Display Webpage

### ISSUE THREAD

**Issue by Forgottenit** [Forgottenit/retro#1]
#3 (INITIAL SETUP)

As a **Site Admin** I can **display my music site** so that **customers can view it**

**ACCEPTANCE CRITERIA**

- Be able to display Home Page

**TASKS**
- [x]  Create basic HTML for Website
- [x]   Link Bootstrap
- [x]  Give basic Style for the pages
- [x]  Create a landing page for the site
- [x]   Create templates and link urls
- [x]   Test site on local and deployed platforms
