### ISSUE TITLE
SEO AND SOCIAL MEDIA

### ISSUE THREAD

**Issue by Forgottenit** [Forgottenit/retro#10]
**TASKS**

- [x] Create a Facebook page for the e-commerce site Link Facebook page to the website
- [x] Set up meta tags for SEO optimization
- [x] Link Facebook page to the website
- [x] Set up a sitemap and robots.txt
