### ISSUE TITLE
DOCUMENTATION

### ISSUE THREAD

**Issue by Forgottenit** [Forgottenit/retro#12]
**TASKS**

- [x] Write a comprehensive README including project setup guide, project structure, feature list, and deployment guide
- [x] Document the code with comments and docstrings
- [x] Create wireframes for UI/UX design 
- [x] Document the design decisions
- [x] Document styling choices and the rationale behind them
