### ISSUE TITLE
Workflow Management

### ISSUE THREAD

**Issue by Forgottenit** [Forgottenit/retro#13]
**TASKS**

- [x] Set up Github Kanban board
- [x] Add tasks to the Kanban board with  labels and document
- [x] Create workflows for the board e.g., todo validate etc. 
- [x] Document
