### ISSUE TITLE
BUGS 

### ISSUE THREAD

**Issue by Forgottenit** [Forgottenit/retro#14]
Site Not Loading in GitHub
Site Not Loading on Heroku

Acceptance Criteria

- Site loads on local host
- Site loads on Heroku

**TASKS**
- [x] Research issue on Slack and StackOverflow
- [x] Backports in requirements for deployment- stackoverflow
- [x] CSRF token in settings for admin 
- [x] Config vars fix errors in Heroku
