### ISSUE TITLE
USER STORIES: Site User 

### ISSUE THREAD

**Issue by Forgottenit** [Forgottenit/retro#15]
- [x] 1. As a site user, I want to be able to browse through various records so that I can decide what to purchase.

- [ ] 2. As a site user, I want to be able to filter and sort my search results so that I can find specific items easily.

- [ ] 3. As a site user, I want to be able to add records to a wishlist or favorites list, so that I can remember them for later.

- [ ] 4. As a site user, I want to be able to add items to a shopping cart, so that I can purchase multiple items at once.

- [ ] 5. As a site user, I want to be able to view my shopping cart and make adjustments (add/remove items, change quantities), so that I have control over what I'm purchasing.

- [ ] 6. As a site user, I want to be able to securely checkout using Stripe, so that I can easily and safely make a purchase.

- [ ] 7. As a site user, I want to be able to create an account, so that I can save my shipping information and preferences.

- [ ] 8. As a site user, I want to be able to subscribe to a newsletter, so that I can receive updates and special offers.

- [ ] 9. As a site user, I want to be able to follow the site on social media, so that I can follow updates and special offers.

- [ ] 10. As a site user, I want the site to ensure data security, so that my information is kept safe.
