### ISSUE TITLE
User Stories: Site Admin

### ISSUE THREAD

**Issue by Forgottenit** [Forgottenit/retro#16]
- [x] 1. As a site admin, I want to be able to manage user accounts so that I can handle any issues that arise.

- [x] 2. As a site admin, I want to be able to view and manage all orders, so that I can check if operations are functioning correctly.

- [x] 3. As a site admin, I want to be able to assist users with their accounts, so that they can have the best experience possible.

- [x] 4. As a site admin, I want to be able to update the site's content, such as sales, new items and announcements, so that users are kept informed.

- [x] 5. As a site admin, I want to be able to handle security threats and issues, to ensure the website and user data are safe.

- [x] 6. As a site admin, I want to manage the inventory, so that I can create new items, edit existing ones, or delete out-of-stock items from the site.

- [x] 7. As a site admin, I want to access popularity data, so that I can analyze trends, identify popular or unpopular items, and plan future inventory purchases or sales.

- [x] 8.  As a Site Admin, I want to manage user accounts and access control, so that I can ensure the security and integrity of the site.
