### ISSUE TITLE
User Stories: Site Marketer

### ISSUE THREAD

**Issue by Forgottenit** [Forgottenit/retro#18]
- [x] 1. As a marketing specialist, I want to create engaging content for a Facebook page to generate interest, potential sales and boost our social media presence.

- [x] 2. As a marketing specialist, I want to create and send newsletters to subscribers, to inform them about new products, promotions, and other relevant updates and to encourage client retention.

- [x] 3. As a marketing specialist, I want to maintain a current and optimized sitemap.xml file, to improve the website visibility and indexing on search engines as part of our SEO strategy.

- [x] 4. As a marketing specialist, I want to maintain a correctly configured robots.txt file, to guide which parts of the site to crawl or not and improve our SEO performance.

- [x] 5. As a marketing specialist, I want to perform keyword research and SEO analysis to improve the site's visibility on search engines.

- [x] 6. As a marketing specialist, I want to set up the right labels for links going to other sites (implement "rel attributes" for external links), so that search engines can understand our site better and it doesn't negatively affect our visibility in search results.
