### ISSUE TITLE
TASK: Create site logo

### ISSUE THREAD

**Issue by Forgottenit** [Forgottenit/retro#19]
As a **Site Owner ** I can **display my logo ** so that **Site users** will recognise my store

**ACCEPTANCE CRITERIA**

- Have a site logo
- Have the site logo displayed as a favicon on the site

**TASKS**

- [ ] Create a site logo
- [ ] Add the logo to images folder
- [ ] Add links to logo in the head section to display logo
