### ISSUE TITLE
ISSUE: Get Fixtures For Site

### ISSUE THREAD

**Issue by Forgottenit** [Forgottenit/retro#20]
**ACCEPTANCE CRITERIA**

- Register for a Spotify API Key
- Setup Your Environment
- Authenticate Your API Requests
- Fetch album data from the Spotify API using the implemented functions.
- Store the fetched album data in a JSON file as fixtures.
- Create a Django view function to read the fixture data from the JSON file.
- Pass the fixture data to the HTML template and render it.
- Display the album details, artists, and tracks in the HTML template using Django template tags and loops.

**TASKS**
- [x] Go to https://developer.spotify.com/dashboard/
- [x] Log in with your Spotify account or create a new one if you don't already have one.
- [x] Accept Terms of Service
- [x] Click on 'Create an App' and fill out the form to register a new application.
- [x] After the application is created, hide the Client ID and Client Secret in env.py 
- [x] Add To settings.py
- [x] Create Spotify App
- [x] Create views.py and urls to fetch albums
- [x] Store albums in json file
- [x] Display items in html
