### ISSUE TITLE
TASK: Register for a Spotify API Key

### ISSUE THREAD

**Issue by Forgottenit** [Forgottenit/retro#21]
**Description:**
Successfully register for a Spotify API Key.

**Acceptance Criteria:**
- Register at https://developer.spotify.com/dashboard/.
- Log in with/ create a Spotify account.
- Accept the Terms of Service.
- Click on "Create an App" and fill out the form to register a new application.

**Tasks:**
- [x] Register for a Spotify API Key.
- [x] Log in with/ create a Spotify account.
- [x] Accept the Terms of Service.
- [x] Click on "Create an App" and fill out the form.
