### ISSUE TITLE
TASK: Implement Authentication and API Request Functions

### ISSUE THREAD

**Issue by Forgottenit** [Forgottenit/retro#23]
**Description:**
Implement authentication and API request functions in `spotify_data.py`.

**Acceptance Criteria:**
- Have a function to authenticate API requests.
- Have a  function to fetch album details from the Spotify API.
- Have a  function to search for albums based on a query.
- Have a function to retrieve album IDs from the search results.

**Tasks:**
- [x] Create the  function to authenticate API requests..
- [x] Create the  function to fetch album details from the Spotify API..
- [x] Create the function to search for albums based on a query..
- [x] Create the function to retrieve album IDs from the search results..
