### ISSUE TITLE
TASK: Create a Django View Function

### ISSUE THREAD

**Issue by Forgottenit** [Forgottenit/retro#26]
**Description:**
Create a Django view function to read the fixture data from the JSON file.

**Acceptance Criteria:**
- Have app to implement views in.
- In new `views.py`, create a view function to read the fixture data from the JSON file.
- Parse the fixture data and pass it to the template context.

**Tasks:**
- [x] Create an app for new views.py
- [x] Add App to settings.py
- [x] Create a view function in `views.py` to read the fixture data.
- [x] Parse the fixture data and pass it to the template context.
