### ISSUE TITLE
TASK: Pass Fixture Data to the HTML Template

### ISSUE THREAD

**Issue by Forgottenit** [Forgottenit/retro#27]
Pass fixture data to the HTML template and render it.

**Acceptance Criteria:**
- Create a HTML template (`album.html`) to display the album details.
- Iterate over the fixture data 
- Generate dynamic HTML content.

**Tasks:**
- [x] Create a HTML template (`album.html`) to display the album details.
- [x] Use Django template and loops to iterate over the fixture data.
- [x]  Generate Bootstrap to display dynamic HTML content.
