### ISSUE TITLE
INITIAL SETUP

### ISSUE THREAD

**Issue by Forgottenit** [Forgottenit/retro#3]
**ACCEPTANCE CRITERIA**

- Have a setup Django project
- Have Django project connected to a production PostgreSql (ElephantSql)
- Have project linked to PostgreSql (psycopg2)
- Have project linked to a production platform (Heroku)
- Link interface with Heroku (Web Server Gateway Interface (WSGI) - Gunicorn)
- Link Cloud Media storage to website (Cloudinary)
- Hide Keys and database (env.py/ gitignore)
- Link Keys to Heroku (Config Vars)
- Deployed site working and displaying locally and on production site
- Document steps in README

**TASKS**

- [x] Create new GitHub Repo
- [x] Install Django
- [x] Create new Django project
- [x] Create new instance in Elephant SQL and link to project
- [x] Install psycopg2
- [x] Create new Heroku App
- [x] Link project to Heroku App (Gunicorn and Procfile)
- [x] Link project to Cloudinary (Django Settings/ Key)
- [x] Create env.py file and hide Keys, and *.sqlite3 add env.py to gitignore
- [x] Link config vars in Heroku
- [x] Create HTML and Templates in Django
- [x] Test templates on local environment
- [x] Deploy site on Heroku
- [x] Test Site on Heroku
- [x] Document Setup in ReadMe
