### ISSUE TITLE
TASK: Create a Form for Updating Albums

### ISSUE THREAD

**Issue by Forgottenit** [Forgottenit/retro#32]
**Description:**
Create a form in the HTML template for updating albums.

**Acceptance Criteria:**
- Have a HTML form to the `album.html` template.
- Have the form to submit a POST request to the views.
- Have form linked to views once appropriate view created. 
- Have an input field for the artist name.
- Have a submit button to trigger the update.

**Tasks:**
- [x] Add a HTML form to the `album.html` template.
- [x] Create Task to create views for POST request and update form once completed.
- [x] Configure the form to submit a POST request to the views.
- [x] Include an input field for the artist name.
- [x] Add a submit button to trigger the update.
