### ISSUE TITLE
TASK: Create the View Function to handle Form Submission

### ISSUE THREAD

**Issue by Forgottenit** [Forgottenit/retro#33]
**Description:**
Implement the `update_albums` view function to handle form submission.

**Acceptance Criteria:**
- In the spotify app `views.py`, have a view function to handle the form submission.
- Retrieve the artist name from the submitted form data.
- Call the `create_fixtures(artist_name)` function from `spotify_data.py` to update the fixtures with new albums.
- Redirect the user back to the album page after updating the fixtures.
- Test albums updated correctly.

**Tasks:**
- [x] Create a view function in `views.py` to handle the form submission.
- [x] Get the artist name from the form submission.
- [x] Call the `create_fixtures(artist_name)` function from `spotify_data.py` to update the fixtures.
- [x] Redirect the user back to the album page after updating the fixtures.
- [x] Test albums updated correctly.
