### ISSUE TITLE
Task 15: Test the Entire Application

### ISSUE THREAD

**Issue by Forgottenit** [Forgottenit/retro#35]
**Description:**
Test the entire application to ensure correct functionality.

**Acceptance Criteria:**
- Run the Django development server `python3 manage.py runserver`.
- Access the album page in a web browser and verify the correct display of albums.
- Test the form submission by entering different artist names and checking if the fixtures are updated accordingly and displayed.

**Tasks:**
- [x] Start the Django development server.
- [x] Access the album page in a web browser and verify the correct display.
- [x] Test the form submission by entering different artist names and checking the fixtures and display.
