### ISSUE TITLE
ISSUE: Create Users App for Accounts

### ISSUE THREAD

**Issue by Forgottenit** [Forgottenit/retro#38]
As a **Site User ** I can **securely log in ** so that **my information can be saved **

**ACCEPTANCE CRITERIA**

- Be able to log in/ log out 
- Be able to set a password and have it stored securely
- Be able to break down users into separate categories 

**TASKS**

- [x] Create an accounts app
- [x] Create models for users (staff, customers etc.)
- [x] Have a login page template 
- [x] test login features
- [x] test create new users
