### ISSUE TITLE
ISSUE: LOADDATA

### ISSUE THREAD

**Issue by Forgottenit** [Forgottenit/retro#41]
As a **SIte Admin** I can **Load data into models ** so that **I can populate the database **

**ACCEPTANCE CRITERIA**

- Be able to load json data into models
- Be able to display data from models

**TASKS**

- [x] Edit models/ json fetch regarding deserialization
- [x] Use album Id as pk? 
- [x] Link models accordingly
