### ISSUE TITLE
TASK: EDIT HTML and CSS for MODELS

### ISSUE THREAD

**Issue by Forgottenit** [Forgottenit/retro#42]
As a **SITE USER ** I can **VIEW MODELS DATA** so that **I CAN SEE EHAT THE SITE HAS**

**ACCEPTANCE CRITERIA**

- Be able to display models html 
- Have it styled

**TASKS**

- [x] Create templates for html
- [x] Link templates
- [x] Have views to display templates
- [x] Test Views and Templates
- [x] Style
