### ISSUE TITLE
ISSUE: HAVE SEARCH FUNCTIONALITY FOR PRODUCTS

### ISSUE THREAD

**Issue by Forgottenit** [Forgottenit/retro#44]
As a **SITE USER ** I can **SEARCH THE SITE ** so that **I CAN FIND THE PRODUCTS I'M LOOKING FOR **

**ACCEPTANCE CRITERIA**

- Be able to search the site
- Have the search return the search item
- Have the items displayed to the user

**TASKS**

- [x] Create a search bar
- [x] Give the search bar an action to relevant product view
- [x] Have the view filter the products by search criteria
- [x] Have the html display the returned items
