### ISSUE TITLE
ISSUE: CREATE MODELS FOR PRODUCTS

### ISSUE THREAD

**Issue by Forgottenit** [Forgottenit/retro#45]
**ACCEPTANCE CRITERIA**

- Be able to store data in created Models 
- Have Models linked to each other in a meaningful way
- Be able to access models in database as admin
- Be able to add and remove items from models
- Store all relevant model data in Database/ Cloudinary 

**TASKS**

- [x] Create Models and fields for Albums
- [x] Link Models to each other for relevant fields
- [x] Test Models in Admin
- [x] Create HTML to view model data
