### ISSUE TITLE
ISSUE: CRUD Functioinality

### ISSUE THREAD

**Issue by Forgottenit** [Forgottenit/retro#46]
As a **Site Owner ** I can ** Add and delete products** so that ** I can remove or add products **

**ACCEPTANCE CRITERIA**

- Be able to delete products
- Be able to Add products 
- Be able to edit products

**TASKS**

- [x] Create views to delete/edit/ add products
- [x] Create form to add/ edit products
- [x] Test Adding and editing products
- [x] Test Deleting products
- [x] TEST DELETING IMAGES FROM MEDIA FOLDER
